/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class jug_ndk_audio_encoder_AudioEncoder */

#ifndef _Included_jug_ndk_audio_encoder_AudioEncoder
#define _Included_jug_ndk_audio_encoder_AudioEncoder
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     jug_ndk_audio_encoder_AudioEncoder
 * Method:    allocate
 * Signature: (III)Z
 */
JNIEXPORT jboolean JNICALL Java_jug_ndk_audio_encoder_AudioEncoder_allocate
  (JNIEnv *, jobject, jint, jint, jint);

/*
 * Class:     jug_ndk_audio_encoder_AudioEncoder
 * Method:    encode
 * Signature: (I[B[B)I
 */
JNIEXPORT jint JNICALL Java_jug_ndk_audio_encoder_AudioEncoder_encode
  (JNIEnv *, jobject, jint, jbyteArray, jbyteArray);

/*
 * Class:     jug_ndk_audio_encoder_AudioEncoder
 * Method:    destroy
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_jug_ndk_audio_encoder_AudioEncoder_destroy
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
